sensor:  
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} HK1 - Vorlauf-Isttemperatur"
    id: ${name}_HK1_Vorlauf_Isttemperatur
    register_type: read
    address: 1030
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    value_type: U_WORD
    filters:
      - multiply: 0.5

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} HK1 - Vorlauf-Solltemperatur"
    id: ${name}_HK1_Vorlauf_Solltemperatur
    register_type: read
    address: 1031
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    value_type: U_WORD
    filters:
      - multiply: 0.5

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} HK1 - Pumpe AN AUS"
    id: ${name}_HK1_Pumpe_AN_AUS
    register_type: coil
    #address: 999 # Heizkreispumpe 0
    address: 1029 # Heizkreispumpe 1 - wrong ?

number:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} HK1 - Gewünschte Vorlauf-temperatur bei -10°C Außentemperatur"
    id: ${name}_HK1_Vorlauf_Temperatur_minus_10C_Aussentemperatur
    address: 1032
    unit_of_measurement: "°C"
    value_type: U_WORD
    multiply: 2
    min_value: 10
    max_value: 110

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} HK1 - Gewünschte Vorlauf-temperatur bei +10°C Außentemperatur"
    id: ${name}_HK1_Vorlauf_Temperatur_10C_Aussentemperatur
    address: 1031
    unit_of_measurement: "°C"
    value_type: U_WORD
    multiply: 2
    min_value: 10
    max_value: 110

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} HK1 - Heizkreispumpe ausschalten wenn Vorlauf Soll kleiner ist als"
    id: ${name}_HK1_Heizkreispumpe_ausschalten_wenn_Vorlauf_Soll_kleiner_ist_als
    address: 1039
    unit_of_measurement: "°C"
    value_type: U_WORD
    multiply: 2
    min_value: 10
    max_value: 30
    
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} HK1 - Absenkung der Vorlauftemperatur im Absenkbetrieb"
    id: ${name}_HK1_Absenkung_der_Vorlauftemperatur_im_Absenkbetrieb
    address: 1033
    unit_of_measurement: "°C"
    value_type: U_WORD
    multiply: 2
    min_value: 0
    max_value: 70
    
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} HK1 - Außentemperatur, unter der die Heizkreispumpe im Heizbetrieb
einschaltet"
    id: ${name}_HK1_Aussentemperatur_unter_der_die_Heizkreispumpe_im_Heizbetrieb_einschaltet
    address: 1036
    unit_of_measurement: "°C"
    value_type: U_WORD
    multiply: 2
    min_value: -20
    max_value: 50

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} HK1 - Außentemperatur, unter der die Heizkreispumpe im Absenkbetrieb einschaltet"
    id: ${name}_HK1_Aussentemperatur_unter_der_die_Heizkreispumpe_im_Absenkbetrieb_einschaltet
    address: 1037
    unit_of_measurement: "°C"
    value_type: U_WORD
    multiply: 2
    min_value: -20
    max_value: 50

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} HK1 - Frostschutztemperatur"
    id: ${name}_HK1_Frostschutztemperatur
    address: 1038
    unit_of_measurement: "°C"
    value_type: U_WORD
    multiply: 2
    min_value: -10
    max_value: 20

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} HK1 - Temp. am Puffer oben ab der der Überhitzungsschutz aktiv wird"
    id: ${name}_HK1_Temp_am_Puffer_oben_ab_der_der_Ueberhitzungsschutz_aktiv_wird
    address: 1047
    unit_of_measurement: "°C"
    value_type: U_WORD
    min_value: 60
    max_value: 120

select:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${name} HK1 - Betriebsart"
    id: ${name}_HK1_Betriebsart
    address: 8046
    value_type: U_WORD
    optionsmap:
      "Aus": 0
      "Automatik": 1
      "Extraheizen": 2
      "Absenken": 3
      "Dauerabsenken": 4
      "Partybetrieb": 5